module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        // Premium soft SaaS color system
        'primary': '#2563EB',
        'primary-light': '#3B82F6',
        'primary-lighter': '#EFF6FF',
        'primary-dark': '#1E40AF',
        
        'background': '#F8FAFC',
        'surface': '#FFFFFF',
        'surface-hover': '#F1F5F9',
        'surface-secondary': '#F8FAFC',
        
        'border': '#E2E8F0',
        'border-light': '#E8EDF7',
        'divider': '#E8EDF7',
        
        'text-primary': '#0F172A',
        'text-secondary': '#64748B',
        'text-tertiary': '#94A3B8',
        'text-muted': '#CBD5E1',
        
        'success': '#10B981',
        'success-light': '#D1FAE5',
        'warning': '#F59E0B',
        'warning-light': '#FEF3C7',
        'error': '#EF4444',
        'error-light': '#FEE2E2',
        'info': '#3B82F6',
        'info-light': '#EFF6FF',

        // Legacy compatibility colors
        "surface-container": "#eaedff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        "tertiary-fixed-dim": "#62df7d",
        "secondary-fixed-dim": "#c3c7cb",
        "tertiary": "#006329",
        "surface-bright": "#faf8ff",
        "outline": "#737686",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2563eb",
        "surface-container-highest": "#dae2fd",
        "outline-variant": "#c3c6d7",
        "on-secondary-container": "#5e6367",
        "on-tertiary-fixed": "#002109",
        "error": "#ba1a1a",
        "tertiary-container": "#007f36",
        "surface-container-high": "#e2e7ff",
        "secondary": "#5a5f62",
        "on-error-container": "#93000a",
        "surface-dim": "#d2d9f4",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005320",
        "on-primary": "#ffffff",
        "secondary-container": "#dce0e4",
        "on-surface": "#131b2e",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed-variant": "#43474b",
        "surface-tint": "#0053db",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#171c1f",
        "on-tertiary-container": "#c7ffca",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed": "#dfe3e7",
        "on-primary-container": "#eeefff",
        "surface-container-low": "#f2f3ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "tertiary-fixed": "#7ffc97",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        sm: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "0.875rem",
        '2xl': "1rem",
        '3xl': "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "sidebar-width": "260px",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
        "stack-lg": "1.5rem",
        "container-max": "1440px",
        "stack-md": "1rem",
      },
      fontSize: {
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-xs": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      boxShadow: {
        'xs': '0 1px 2px 0 rgba(15, 23, 42, 0.03)',
        'sm': '0 1px 3px 0 rgba(15, 23, 42, 0.08), 0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        'md': '0 4px 6px -1px rgba(15, 23, 42, 0.1), 0 2px 4px -1px rgba(15, 23, 42, 0.06)',
        'lg': '0 10px 15px -3px rgba(15, 23, 42, 0.1), 0 4px 6px -2px rgba(15, 23, 42, 0.05)',
        'xl': '0 20px 25px -5px rgba(15, 23, 42, 0.1), 0 10px 10px -5px rgba(15, 23, 42, 0.04)',
        'glow': '0 0 20px rgba(37, 99, 235, 0.2)',
      },
      animation: {
        'fadeIn': 'fadeIn 0.3s ease-in-out',
        'slideUp': 'slideUp 0.3s ease-out',
        'pulse-soft': 'pulse-soft 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.8' },
        },
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
      },
    },
  },
  plugins: [],
}
