module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eaedff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        "tertiary-fixed-dim": "#62df7d",
        "secondary-fixed-dim": "#c3c7cb",
        "tertiary": "#006329",
        "surface-bright": "#faf8ff",
        "primary": "#004ac6",
        "outline": "#737686",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2563eb",
        "surface": "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "outline-variant": "#c3c6d7",
        "on-secondary-container": "#5e6367",
        "on-tertiary-fixed": "#002109",
        "error": "#ba1a1a",
        "tertiary-container": "#007f36",
        "surface-container-high": "#e2e7ff",
        "secondary": "#5a5f62",
        "on-error-container": "#93000a",
        "surface-dim": "#d2d9f4",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005320",
        "on-primary": "#ffffff",
        "secondary-container": "#dce0e4",
        "on-surface": "#131b2e",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary-fixed-variant": "#43474b",
        "surface-tint": "#0053db",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#171c1f",
        "on-tertiary-container": "#c7ffca",
        "on-surface-variant": "#434655",
        "primary-fixed": "#dbe1ff",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed": "#dfe3e7",
        "on-primary-container": "#eeefff",
        "surface-container-low": "#f2f3ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "tertiary-fixed": "#7ffc97",
        "background": "#faf8ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "sidebar-width": "240px",
        "margin-mobile": "1rem",
        gutter: "1.5rem",
        "stack-lg": "1.5rem",
        "container-max": "1440px",
        "stack-md": "1rem",
      },
      fontFamily: {
        "title-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-base": ["Inter"],
        "label-md": ["Inter"],
        "label-xs": ["Inter"],
        code: ["JetBrains Mono"],
        "display-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-xs": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
